name: 游 Deploy Angular App

on:
  push:
    branches:
      - main   # ou master, usa o nome da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar reposit칩rio
        uses: actions/checkout@v4

      - name: 游릭 Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 游닍 Instalar depend칡ncias
        run: npm install

      - name: 游댣 Build do Angular
        run: npm run build -- --configuration production

      - name: 游 Deploy no Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy autom치tico"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}